---
- hosts: web
  vars:
     site_name: hitman959.devops.srwx.net
     email: hitman959@gmail.com

  tasks:
  - name: Installing packages
    apt: name={{item}} state=latest
    with_items:
        - nginx
        - php-fpm
        - git
        - golang
        - letsencrypt
      
  - name: Remove default config
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify: restart nginx
   
  - name: Install https site config
    template: src=templates/{{site_name}}.j2 dest=/etc/nginx/sites-available/{{site_name}} owner=root group=root mode=0644
    notify: restart nginx

  - name: Create link https site
    file: src=/etc/nginx/sites-available/{{site_name}} dest=/etc/nginx/sites-enabled/{{site_name}} state=link owner=root group=root mode=0644
    notify: restart nginx

  - name: Install http site config
    template: src=templates/{{site_name}}.http.j2 dest=/etc/nginx/sites-available/{{site_name}}.http owner=root group=root mode=0644
    notify: restart nginx

  - name: Create link
    file: src=/etc/nginx/sites-available/{{site_name}}.http dest=/etc/nginx/sites-enabled/{{site_name}}.http state=link owner=root group=root mode=0644
    notify: restart nginx

  - name: Add folder to acme
    file: path=/srv/acme state=directory

  - name: Recieve SSL sertificates
    shell: letsencrypt certonly --non-interactive --agree-tos --webroot -w /srv/acme -d {{site_name}} --email {{email}}
    creates: /etc/letsencrypt/live/{{site_name}}/fullchain.pem 

  - name: Clone goapp-web
    git:
     repo: https://github.com/Hitman95/goapp-web.git
     dest: /srv/goapp-web
     clone: yes

  - name: Clone goapp-api
    git:
     repo: https://github.com/Hitman95/goapp-api.git
     dest: /srv/goapp-api
     clone: yes

  - name: Clone phpapp
    git:
     repo: https://github.com/Hitman95/phpapp.git
     dest: /srv/phpapp
     clone: yes

  - name: Install goapp-api service 
    template: src=templates/goapp-api.service.j2 dest=/etc/systemd/system/goapp-api.service owner=root group=root
    notify: start goapp-api

  handlers:
    - name: start goapp-api
      service: name=goapp-api state=reloaded enabled=yes

    - name: restart nginx
      service: name=nginx state=restarted

