
- hosts: web
  tasks:
  - name: Installing packages
    apt: name={{item}} state=latest
    with_items:
        - nginx
        - php-fpm
        - git
        - golang
      
  - name: Remove default config
    file: path=/etc/nginx/sites-enabled/default state=absent

